export type Screen =
  | "dashboard"
  | "students"
  | "sheikhs"
  | "halaqat"
  | "branches"
  | "roles"
  | "users"
  | "reports"
  | "activity"
  | "notifications"
  | "settings"
  | "student"
  | "entity"
  | "login"

export type EntityType = "sheikhs" | "halaqat" | "branches" | "roles" | "users"

export type FormKind = "student" | "sheikh" | "halaqa" | "branch" | "role" | "user"

export type IconName =
  | "home"
  | "people"
  | "book"
  | "branch"
  | "shield"
  | "chart"
  | "clock"
  | "bell"
  | "settings"
  | "search"
  | "plus"
  | "filter"
  | "download"
  | "more"
  | "chevron"
  | "menu"
  | "close"
  | "check"
  | "user"
  | "logout"
  | "calendar"
  | "school"
  | "phone"
  | "mail"
  | "arrow"
  | "edit"
  | "command"
  | "error"
  | "warning"
  | "info"
  | "upload"
  | "activity"
  | "userCog"
  | "moon"
  | "sun"
