import {
  Activity as ActivityIcon,
  ArrowLeft,
  Bell,
  BookOpen,
  Building2,
  CalendarDays,
  ChartNoAxesCombined,
  Check,
  ChevronDown,
  CircleX,
  Clock3,
  Command,
  FileDown,
  Filter,
  GraduationCap,
  Home,
  Info,
  LogOut,
  Mail,
  Menu,
  MoreHorizontal,
  Moon,
  Pencil,
  Phone,
  Plus,
  Search,
  Settings as SettingsIcon,
  ShieldCheck,
  Sun,
  TriangleAlert,
  Upload,
  UserCog,
  UserRound,
  UsersRound,
  X,
  type LucideIcon,
} from "lucide-react"
import type { IconName } from "@/types"

export const icons: Record<IconName, LucideIcon> = {
  home: Home,
  people: UsersRound,
  book: BookOpen,
  branch: Building2,
  shield: ShieldCheck,
  chart: ChartNoAxesCombined,
  clock: Clock3,
  bell: Bell,
  settings: SettingsIcon,
  search: Search,
  plus: Plus,
  filter: Filter,
  download: FileDown,
  more: MoreHorizontal,
  chevron: ChevronDown,
  menu: Menu,
  close: X,
  check: Check,
  user: UserRound,
  logout: LogOut,
  calendar: CalendarDays,
  school: GraduationCap,
  phone: Phone,
  mail: Mail,
  arrow: ArrowLeft,
  edit: Pencil,
  command: Command,
  error: CircleX,
  warning: TriangleAlert,
  info: Info,
  upload: Upload,
  activity: ActivityIcon,
  userCog: UserCog,
  moon: Moon,
  sun: Sun,
}

export function Icon({ name, size = 20 }: { name: IconName; size?: number }) {
  const Lucide = icons[name]
  if (!Lucide) return null
  return (
    <Lucide aria-hidden="true" className="icon" size={size} strokeWidth={1.8} />
  )
}
